trigger: none
pr: none

pool:
  vmImage: windows-latest

stages:
- stage: terraform_validate
  displayName: Prepare Terraform and Validate Code
  jobs:
  - job:
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    - task: TerraformCLI@0
      displayName: Terraform init
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'terraform-github-actions'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'Terraform-Github-Actions'
        backendAzureRmResourceGroupLocation: 'eastus'
        backendAzureRmStorageAccountName: 'terraformgtactions'
        backendAzureRmStorageAccountSku: 'Standard_LRS'
        backendAzureRmContainerName: 'tfstates'
        backendAzureRmKey: 'dev-tfstate'
        allowTelemetryCollection: false
        commandOptions: '-var-file="dev/main.tfvars"'
    - task: TerraformCLI@0
      displayName: Terraform validate
      inputs:
        command: 'validate'
        environmentServiceName: 'terraform-github-actions'
        allowTelemetryCollection: false

- stage: terraform_plan
  dependsOn: terraform_validate
  condition: succeeded('terraform_validate')
  displayName: Prepare Terraform and Validate Code
  jobs:
  - job:
    steps:  
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    - task: TerraformCLI@0
      displayName: Terraform init
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'terraform-github-actions'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'Terraform-Github-Actions'
        backendAzureRmResourceGroupLocation: 'eastus'
        backendAzureRmStorageAccountName: 'terraformgtactions'
        backendAzureRmStorageAccountSku: 'Standard_LRS'
        backendAzureRmContainerName: 'tfstates'
        backendAzureRmKey: 'dev-tfstate'
        allowTelemetryCollection: false
        commandOptions: '-var-file="dev/main.tfvars"'   
    - task: TerraformCLI@0
      displayName: Terraform plan
      inputs:
        command: 'plan'
        environmentServiceName: 'terraform-github-actions'
        allowTelemetryCollection: false
        commandOptions: '-var-file="dev/main.tfvars"'
  
- stage: terraform_apply
  condition: succeeded('terraform_plan')
  dependsOn: terraform_plan
  displayName: Prepare Terraform and Validate Code
  jobs:
  - job:
    steps:     
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    - task: TerraformCLI@0
      displayName: Terraform init
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'terraform-github-actions'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'Terraform-Github-Actions'
        backendAzureRmResourceGroupLocation: 'eastus'
        backendAzureRmStorageAccountName: 'terraformgtactions'
        backendAzureRmStorageAccountSku: 'Standard_LRS'
        backendAzureRmContainerName: 'tfstates'
        backendAzureRmKey: 'dev-tfstate'
        allowTelemetryCollection: false
        commandOptions: '-var-file="dev/main.tfvars"'   
    - task: TerraformCLI@0
      displayName: Terraform apply
      inputs:
        command: 'apply'
        environmentServiceName: 'terraform-github-actions'
        commandOptions: '-var-file="dev/main.tfvars"'
        allowTelemetryCollection: false